model:
    type: vae
    data: volsurfaces
    beta: 0.01

train:
    batch_size: 128
    epochs: 20
    learning_rate: 0.02

network:
    latent_dim: 4
    input_dim: 72
    hidden_dim: 64


hypertune:
    learning_rate:
        - 0.001
        - 0.0001
    # batch_size:
    #     - 64
    #     - 128
    # latent_dim:
    #     - 10
    #     - 20
    # hidden_dim:
    #     - 50
    #     - 100
